//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Passport { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> LastOnline { get; set; }
        public Nullable<int> EntryTypeID { get; set; }
        public int GenderID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual Type Type { get; set; }
    }
}
